FROM ubuntu:22.04
RUN apt-get update
RUN apt-get -y install make
RUN apt-get -y install vim
RUN apt-get -y install git
RUN apt-get -y install python3
RUN apt-get -y install default-jdk
RUN apt-get -y install junit4
RUN apt-get -y install ant